name: Check Shell Scripts

on:
  pull_request:

jobs:
  check-shells:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check shell scripts
        uses: ./check-shells
